apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-company
spec:
  selector:
    matchLabels:
      app: company
  replicas: 1
  template:
    metadata:
      labels:
        app: company
    spec:
      containers:
        - name: company
          image: ${REPOSITORY_TAG}
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            successThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ms-company
spec:
  selector:
    app: company
  ports:
    - name: http
      port: 9092

  type: LoadBalancer